Lab23-SWAPI/Models/ErrorViewModel.cs
using System;

namespace Lab23_SWAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab23-SWAPI/Models/People.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab23_SWAPI.Models
{
    public class People
    {
        //map properties to JSON output
        public string Name { get; set; }
        public string Height { get; set; }
        public string Mass { get; set; }
        public string Hair_Color { get; set; }
        public string Skin_Color { get; set; }
        public string Eye_Color { get; set; }
        public string Birth_Year { get; set; }
        public string Gender { get; set; }
        public string Homeworld { get; set; }

        public string[] Films { get; set; }
        public string[] Vehicles { get; set; }
        public string[] Starships { get; set; }
    }
}

Lab23-SWAPI/Models/Planet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab23_SWAPI.Models
{
    public class Planet
    {
        //map planet properties

        public string Name { get; set; }

        public string Rotation_Period { get; set; }
        public string Orbital_Period { get; set; }
        public string Diameter { get; set; }
        public string Climate { get; set; }
        public string Gravity { get; set; }
        public string Terrain { get; set; }
        public string Surface_Water { get; set; }
        public string Population { get; set; }

        public string[] Residents { get; set; }
        
        public string[] Films { get; set; }
    }

   
}

Lab23-SWAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Lab23_SWAPI.Models;

namespace Lab23_SWAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab23-SWAPI/Controllers/StarWarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Lab23_SWAPI.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab23_SWAPI.Controllers
{
    public class StarWarsController : Controller
    {
        public IActionResult Index(string personId, string planetId)
        {
            if(personId != null)
            {
                return RedirectToAction("Person", personId);
            }
            else if (planetId != null)
            {
                return RedirectToAction("Planet", planetId);
            }

            return View();
        }

        public async Task<IActionResult> Person(int id)
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://swapi.co/api/");

            var response = await client.GetAsync($"people/{id}/");
            //var response = await client.GetAsync($"people/1/");
            var person = await response.Content.ReadAsAsync<People>();

            return View(person);
        }

        public async Task<IActionResult> Planet(int id)
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://swapi.co/api/");

            var response = await client.GetAsync($"planets/1/");
            //var response = await client.GetAsync($"planet/{id}/");
            var planet = await response.Content.ReadAsAsync<Planet>();

            return View(planet);
        }



    }
}

Lab23-SWAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab23-SWAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab23_SWAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab23_SWAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StarWars" asp-action="Index">Star Wars Index!</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Lab23_SWAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Lab23-SWAPI/Views/StarWars/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form action="../StarWars/Person" method="post">
    Search by person id: <input type="search" name="id" value="" />
    <input type="submit" />
</form>
<form action="../StarWars/Planet" method="post">
    Search by planet id: <input type="search" name="id" value="" />
    <input type="submit" />
</form>

Lab23-SWAPI/Views/StarWars/Person.cshtml
@{
    ViewData["Title"] = "Person";
}
@model People 
    
    <!--What a terrible class name...-->

<h1>Person</h1>

 <!--Setup table to display person's stats
     Handling -->

@Model.Name

<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <th>Height</th>
        <td>@Model.Height Wipples</td>
    </tr>
    <tr>
        <th>Weight</th>
        <td>@Model.Mass Jeffersons</td>
    </tr>
    <tr>
        <th>Homeworld</th>
        <td>@Model.Homeworld</td>
    </tr>
    <tr>
        <th>Favorite Vehicles:</th>
        <td>
            @foreach (string v in Model.Vehicles)
            {
                <div>@v</div>
            }
        </td>
    </tr>
    <tr>
        <th>Appears in:</th>
        <td>
            @foreach (string f in Model.Films)
            {
                <div>@f</div>
            }
        </td>
    </tr>

</table>

Lab23-SWAPI/Views/StarWars/Planet.cshtml
@{
    ViewData["Title"] = "Planet";
}

@model Planet

<h1>Planet</h1>

<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <th>Rotational Period</th>
        <td>@Model.Rotation_Period Days</td>
    </tr>
    <tr>
        <th>Orbital Period</th>
        <td>@Model.Orbital_Period Days</td>
    </tr>
    <tr>
        <th>Climate</th>
        <td>@Model.Climate</td>
    </tr>
    <tr>
        <th>Population</th>
        <td>@Model.Population</td>
    </tr>
    <tr>
        <th>Residents</th>
        <td>
            @foreach (string p in Model.Residents)
            {
            <div>@p</div>
            }
        </td>
    </tr>


</table>